version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: npm run dev
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
