name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend
      - name: Run tests
        run: pytest
      - name: Build frontend
        run: npm run build
        working-directory: frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend
